codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no